### ISSUE TITLE
Inventory name bug?

### ISSUE THREAD

**Issue by FairGames** [2lstudios-mc/Crates#3]
inventory:
  title: "&eCrate %displayname%"
  
 https://gyazo.com/d2caf81d86a3ba86f8e230aca4798da7

**Comment by FairGames** [comment]
Hologram position
https://gyazo.com/ffe0d04ee820f0d89a32f9d048d3898f

**Comment by linsaftw** [comment]
What version is your server in?

**Comment by FairGames** [comment]
FlamePaper^^

**Comment by linsaftw** [comment]
Weird. Maybe the name is too large?

**Comment by yiyoperez** [comment]
Title is not long, Inventory title is never being set, this one being created at [this](https://github.com/2lstudios-mc/Crates/blob/bd61892cb83f85ef5973107cda3dcc106cee0fd0/src/dev/_2lstudios/crates/crate/Crate.java#L200) line

**Comment by linsaftw** [comment]
I see. Adding the missing config text.

**Comment by linsaftw** [comment]
Done. Now i need to update.
