### ISSUE TITLE
Suggestions about rewards

### ISSUE THREAD

**Issue by Baba0bab** [2lstudios-mc/Crates#4]
Hello, I have some suggestions for your plugin:

- An option for a reward is not necessarily to give an item, but an option for a command to be executed, for example: giving money to a player or earning a rank
- Manage the chance that a player can have a certain reward for example: 1/10 to have a stack of obsidian and 9/10 to have a stack of cobble

Hopefully you will find them interesting and maybe it will happen on the plugin.
Baba.

**Comment by linsaftw** [comment]
Please separate your suggestions into two separate issues. Thanks.
