### ISSUE TITLE
Configurable hologram position

### ISSUE THREAD

**Issue by FairGames** [2lstudios-mc/Crates#8]
Add holo height
or stacked from bottom

Thanks <3

![image](https://user-images.githubusercontent.com/96260907/206799586-a7548900-7777-4b69-af53-662d19f86735.png)
![image](https://user-images.githubusercontent.com/96260907/206799592-fdc6d07d-f54b-4510-8716-2fef13a4e32c.png)

**Comment by linsaftw** [comment]
Thank you very much. I will add a customization for the height of the hologram.

**Comment by linsaftw** [comment]
Done. New update will have an automatic offset.
